from bibliotecaPOO import *

p1 = Pessoa("Felipe", 81, 23)
p1.comer("Maçã")
p1.falar("Ingles")
p1.dormir()
print()
g1 = Gato("Neko", "Branca")
g1.comer()
g1.miar()
print()
c1 = Cachorro("Scooby", "Marrom")
c1.comer()
c1.latir()
print()
v1 = Vaca("Mimosa", "preta e branca")
v1.comer()
v1.mugir()
print()
cc1 = Corredor("Felipe", 81)
cc1.aquecer()
cc1.correr()
print()
n1 = Nadador("Felipe", 81)
n1.aquecer()
n1.nadar()
print()
ci1 = Ciclista("Felipe", 81)
ci1.aquecer()
ci1.pedalar()
print()
tri1 = Triatleta("Felipe", 81)
tri1.desaposentar()
tri1.nadar()
tri1.aquecer()
tri1.nadar()
tri1.aposentar()
tri1.correr()
tri1.desaposentar()
tri1.correr()
tri1.aquecer()
tri1.correr()
print()
cont = 0
while cont == 0:
    num = int(input("1 - Gravar texto\n2 - Ler texto\n3 - Sair\n"))
    if num == 1:
        texto = input("Digite um texto: ")
        gravar_texto(texto)
    elif num == 2:
        ler_texto()
    elif num == 3:
        print("Fim do programa")
        cont += 1
    else:
        print("Opção indisponível")
