from bibliotecaPOO import *

p1 = Pessoa("Felipe", 81, 23)
p1.comer("Maçã")
p1.falar("Ingles")
p1.dormir()
print()
g1 = Gato("Neko", "Branca")
g1.comer()
g1.miar()
print()
c1 = Cachorro("Scooby", "Marrom")
c1.comer()
c1.latir()
print()
v1 = Vaca("Mimosa", "preta e branca")
v1.comer()
v1.mugir()